# Generated by Django 4.2.3 on 2023-07-26 16:20

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_banner_upload_path
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icons",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_icon_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.category_icon_upload_path
            ),
        ),
    ]
